var numero1 = Number(prompt("digite o primeiro numero"))
var numero2 = Number(prompt("digite o segundo numero")) 
     console.log( numero1 + numero2) 
var numero3 = Number(prompt("digite o primeiro numero"))
var numero4 = Number(prompt("digite o segundo numero"))    
       console.log(numero3 - numero4)
var numero5 = Number(prompt("digite o primeiro numero"))
var numero6 = Number(prompt("digite o segundo numero"))
      console.log( numero5 * numero6)
var numero7 = Number(prompt("digite o primeiro numero"))
var numero8 = Number(prompt("digite o segundo numero")) 
       console.log(numero7 / numero8) 